### ISSUE TITLE
Line numbers should be preserved

### ISSUE THREAD

**Issue by JayFoxRox** [jarikomppa/interjector#1]
I have not tried this tool yet, but looking over the README I did notice that it added a new line for `FUNCTION_ENTRY`. This is not good, because one could no longer use `__LINE__` to find out where one is (in the original code).

By preserving line numbers, the Makefile could add the macros without the users knowledge before sending code to the compiler. So the user could follow code in the original file while running the modified code.

**Comment by jarikomppa** [comment]
This could be done by tracking which input line we're on and throwing #line primitives, as needed.

**Comment by jarikomppa** [comment]
#line primitives are now sent. May be off by one, did not test actual debugging, but should be better than before.
