### ISSUE TITLE
Argument to macro can be avoided

### ISSUE THREAD

**Issue by JayFoxRox** [jarikomppa/interjector#2]
The argument to the macro could be avoided, because macros like `__FUNCTION__` or `__PRETTY_FUNCTION__` do commonly exist. C99 also has `__func__`.

This would simplify the code.

**Comment by jarikomppa** [comment]
I suppose, but having the parameter doesn't really do any harm.. I used this on a platform that also only supported some really ancient compiler, so those macros were not available.
